#!/usr/bin/env python3
"""Archive a completed active task into progress logs and reset active-task."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
import argparse
import re
import sys


ROOT = Path(__file__).resolve().parents[2]
ACTIVE_TASK = ROOT / "memory-bank" / "runtime" / "active-task.md"
ACTIVE_TASK_TEMPLATE = ROOT / "memory-bank-templete" / "runtime" / "active-task.template.md"
PROGRESS_ROOT = ROOT / "memory-bank" / "logs" / "progress"
TASK_ID_PATTERN = re.compile(r"^## Task ID\s*$", re.MULTILINE)


def now_local() -> datetime:
    return datetime.now().astimezone()


def slugify(value: str) -> str:
    value = value.strip().lower()
    value = re.sub(r"[^a-z0-9\u4e00-\u9fff-]+", "-", value)
    return value.strip("-") or "active-task"


def extract_section(text: str, heading: str) -> str:
    pattern = re.compile(rf"^## {re.escape(heading)}\s*$", re.MULTILINE)
    match = pattern.search(text)
    if not match:
        return ""
    start = match.end()
    next_match = re.search(r"^## ", text[start:], re.MULTILINE)
    end = start + next_match.start() if next_match else len(text)
    return text[start:end].strip()


def task_id(text: str) -> str:
    return slugify(extract_section(text, "Task ID").splitlines()[0] if extract_section(text, "Task ID") else "active-task")


def is_completed(text: str) -> bool:
    status = extract_section(text, "Current Status").lower()
    checklist = extract_section(text, "Checklist")
    unchecked = re.search(r"^- \[ \]", checklist, re.MULTILINE)
    checked = re.search(r"^- \[x\]", checklist, re.MULTILINE | re.IGNORECASE)
    status_done = any(word in status for word in ["completed", "done", "已完成", "完成"])
    return status_done or (checked is not None and unchecked is None)


def archive_path(task_slug: str, current_time: datetime) -> Path:
    base = PROGRESS_ROOT / f"{current_time:%Y-%m-%d}-{task_slug}.md"
    if not base.exists():
        return base
    for index in range(2, 100):
        candidate = PROGRESS_ROOT / f"{current_time:%Y-%m-%d}-{task_slug}-{index}.md"
        if not candidate.exists():
            return candidate
    raise RuntimeError("could not find available archive filename")


def archive_content(active_text: str, current_time: datetime) -> str:
    return f"""---
type: paradigma-progress-log
title: Archived Active Task
description: Archived active task generated by pd-archive-task.py.
tags: [progress, archive, active-task]
timestamp: {current_time.isoformat(timespec='seconds')}
paradigma:
  layer: logs
  lifecycle: append-only
  update_policy: append-only
  source: memory-bank/runtime/active-task.md
---

# Archived Active Task

Archived at: {current_time:%Y-%m-%d %H:%M}

{active_text.strip()}
"""


def reset_active_task(current_time: datetime) -> None:
    template = ACTIVE_TASK_TEMPLATE.read_text(encoding="utf-8-sig")
    content = template.replace("YYYY-MM-DDTHH:mm:ssZ", current_time.isoformat(timespec="seconds"))
    ACTIVE_TASK.write_text(content, encoding="utf-8", newline="\n")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="archive and reset active-task")
    parser.add_argument("--force", action="store_true", help="archive even when active-task does not look completed")
    args = parser.parse_args()

    if not ACTIVE_TASK.exists():
        print(f"ERROR: missing {ACTIVE_TASK.relative_to(ROOT)}")
        return 1
    active_text = ACTIVE_TASK.read_text(encoding="utf-8-sig")
    completed = is_completed(active_text)
    if not completed and not args.force:
        print("ERROR: active task does not look completed; use --force to archive anyway.")
        return 1

    current_time = now_local()
    target = archive_path(task_id(active_text), current_time)
    print(f"Archive target: {target.relative_to(ROOT)}")
    if not args.write:
        print("Dry run only. Pass --write to archive and reset active-task.")
        return 0

    PROGRESS_ROOT.mkdir(parents=True, exist_ok=True)
    target.write_text(archive_content(active_text, current_time), encoding="utf-8", newline="\n")
    reset_active_task(current_time)
    print(f"Archived active task and reset {ACTIVE_TASK.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
